version: '3.2'

services:

  wordpress:
    image: wordpress:5.0.3-php7.1-apache
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: dbuser
      WORDPRESS_DB_PASSWORD: dbpass
      WORDPRESS_DB_NAME: vincent_db
    volumes:
      - ./themes:/var/www/html/wp-content/themes/
      - ./plugins:/var/www/html/wp-content/plugins/


  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: vincent_db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      MYSQL_RANDOM_ROOT_PASSWORD: 'marcelo'